### PR TITLE
Feature/test

### PR DESCRIPTION
**Pull request by meme-es**
This feature branch adds the /spec/enumerable_spec.rb file which is to test every enumerable method.

The test runs typing rspec command in a terminal

### CODE REVIEW

**Comment by meme-es** [comment]
This is just a comment test.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @meme-es :lollipop: 

### You've done an incredible work with your test cases :1st_place_medal:  so you should feel very proud of them, I think most of the requirements were beyond met there's only one aspect to work on :construction: :construction_worker: 

* [x] cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) 

- All your test cases are positive, so let's add some negative test cases at least for the boolean scenarios

For example, this test case could be changed to be negative by changing the description to start with a negative word and use the not_to method

```ruby
#Positive
        it 'returns false if any element has the same value' do
          expect(numbers.my_none?(3)).to eql(numbers.none?(3))
        end
#Negative
        it "doesn't return true if any element has the same value" do
          expect(numbers.my_none?(3)).not_to eql(true)
        end
```

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by meme-es** [comment]
Thank you @euqueme for the feedback and useful suggestions, I made the changes.

**Review by whiz25 — APPROVED** [review]
## Approved :clap:
You have successfully implemented the suggestions made by the previous reviewer. Merge and move forward.

### Martin Afani

**Comment by meme-es** [comment]
Thank you @whiz25

**Pull request merged**
